apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c7hj6j7w2-java-springboot
  janus-idp.io/tekton: c7hj6j7w2-java-springboot
  backstage.io/kubernetes-id: c7hj6j7w2-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c7hj6j7w2-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
